### PR TITLE
add to malicious packages already taken down from NPM

### PR DESCRIPTION
**Pull request by yeiniel**

### CODE REVIEW

**Comment by spaceraccoon** [comment]
Thank you so much @yeiniel ! I will add a markdown file describing their contents (e.g. https://github.com/spaceraccoon/npm-zoo/blob/master/packages/portionfatty12/README.md). Please let me know if there's any more info I should add into the "Summary" section.

**Comment by yeiniel** [comment]
I try to add the files in the correct folder structure but there was a gitignore rule that prevent adding all the package files and therefore I opt for adding compressed versions of the packages.

**Comment by spaceraccoon** [comment]
Got it, I will fix the gitignore!

**Comment by DanielRuf** [comment]
I wonder if there will be more in the future.
The lack of IoCs from npm Inc and others makes it hard to scan projects for malicious code.

So far I also have the eslint-scope package as compressed tarball.

**Pull request merged**
